# 복습문제

In [5]:
from nltk.stem import PorterStemmer
from nltk import word_tokenize

porter = PorterStemmer()

text =  "Now I am going to have dinner with my wife. Thanks for having me here."

words = word_tokenize(text)

li = []

for word in words:
    st_word = stemmer.stem(word)
    li.append(st_word)
    
li

['now',
 'i',
 'am',
 'go',
 'to',
 'have',
 'dinner',
 'with',
 'my',
 'wife',
 '.',
 'thank',
 'for',
 'have',
 'me',
 'here',
 '.']

In [6]:
# porter.stem(word) for word in words

In [7]:
sentence = "Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop. "

len(word_tokenize(sentence))

25

In [8]:
[ [ 0 0 0 0 0 0 ]
  [ 0 0 0 0 0 0 ]
  [ 0 0 0 5 2 0 ]
  [ 0 0 3 0 0 0 ]
  [ 0 0 0 0 0 0 ] ]

In [12]:
from scipy import sparse

# 1. COO 형식으로

import numpy as np

data = np.array([5, 2, 3])
row = np.array([2, 2, 3])
col = np.array([3, 4, 2])

print(sparse.coo_matrix((data, (row, col)), shape=(5, 6)).toarray())

# 2. CSR 형식으로

data = [5, 2, 3]
row_ = [2, 2, 3]
col = [3, 4, 2]

sparse.csr_matrix((data, (row_, col)), (5, 6)).toarray() 

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 5 2 0]
 [0 0 3 0 0 0]
 [0 0 0 0 0 0]]


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 5, 2, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)

In [ ]:
문서와 문서 간의 유사도 비교는 일반적으로 (  ) 를 사용한다. (  ) 에 들어갈 말은?

코사인 유사도(cosine similarity)

In [ ]:
문서 집합에 숨어 있는 주제를 찾아내는 모델링 방법은?

토픽 모델링

In [ ]:
텍스트 분석 패키지 중 주로 소셜 미디어 텍스트에 대한 감성분석을 제공하고, 뛰어난 감성 분석 결과 및 빠른 수행시간으로 대용량 텍스트 데이터에 잘 사용되는 패키지는?

VADER(베이더)

In [ ]:
자연어를 기계가 이해할 수 있는 숫자의 나열인 벡터로 바꾸어 주어야 한다. 이것을 뜻하는 말은?

피처 벡터화 또는 워드 임베깅

In [ ]:
두 문장에서 같은 단어가 자주 나타나면 코사인 유사도가 높다? 낮다?

높다

In [ ]:
KMeans 객체의 clusters_centers 속성은 0에서 1의 값을 가지며 0에 가까울수록 중심에 가까운 값이다? O/X

X

In [ ]:
[ [ 1, 2, 0, 0, 0, 0 ]
  [ 0, 0, 0, 0, 0, 0 ]
  [ 0, 0, 4, 5, 2, 0 ]
  [ 0, 0, 0, 0, 0, 0 ]
  [ 0, 0, 3, 0, 0, 0 ] ]

In [13]:
data = np.array([1,2,4,5,2,3])
row_in = np.array([0,2,2,5,5,6])
col = np.array([0,1,2,3,4,2])
sparse.csr_matrix((data,col,row_in),shape=(5,6)).toarray() 

array([[1, 2, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 4, 5, 2, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0]])